rawData <- read.table("household_power_consumption.txt", sep=";", header=TRUE, colClasses=c('character', 'character', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric'), na.strings=c('?'))
rawData$DateTime <- strptime(paste(rawData$Date, rawData$Time), format="%d/%m/%Y %H:%M:%S")
data <- rawData[rawData$DateTime>=strptime('2007-02-01', format='%Y-%m-%d') & rawData$DateTime<strptime('2007-02-03', format='%Y-%m-%d'),]
par(mfrow=c(2,2))
with(data, {
   plot(DateTime, Global_active_power, type='l', xlab='', ylab='Global Active Power (kilowatts)')
   plot(DateTime, Voltage, type='l', xlab='datetime')
   plot(data$DateTime, data$Sub_metering_1, type='l', xlab='', ylab='Engery sub metering', col='black')
   lines(data$DateTime, data$Sub_metering_2, col='red')
   lines(data$DateTime, data$Sub_metering_3, col='blue')
   legend('topright', lty=1, col=c('black', 'red', 'blue'), legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'))
   plot(DateTime, Global_reactive_power, type='l', xlab='datetime')
})
dev.copy(png, file='plot4.png')
dev.off()
